services:
  - type: web
    name: django-pricing
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn DjangoPricingApp.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DjangoPricingApp.settings